name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v3

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Vérifier syntaxe PHP
        run: php -l index.php

      - name: Construire image Docker
        run: docker build -t projet-devops .
